routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\Staff1Controller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerExportController;
use App\Http\Controllers\CustomerImportController;

use App\Mail\WelcomeMail;


use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;


// use App\Http\Controllers\RoleController;
// use App\Http\Controllers\UserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/emails',function()
{
	Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail());
	return new WelcomeMail();
});

// Route::get('/emails', function () {
   
//     $customer = [
//         'name' => 'Mail from ItSolutionStuff.com',
//         'info' => 'This is for testing email using smtp'
//     ];
   
//     \Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail($customer));
   
// });

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
// Route::resource('admin/customer', CustomerController::class);


// Route::middleware(['auth:sanctum', 'verified'])->get('/customer.index', function () {
//     return view('customer');
// })->name('customer');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function()

{
Route::get('/dashboard', [HomeController::class, 'index'])->name('home');


	Route::get('staff',[Staff1Controller::class,'index'])->name('staff');

	Route::resource('customer',CustomerController::class);

	
	Route::resource('categorys',CategoryController::class);
	Route::resource('products',ProductController::class);



  Route::get('/export', [CustomerController::class, 'export'])->name('CustomerController.export');
    Route::get('/import-form', [CustomerController::class, 'importform'])->name('CustomerController.import-form');
    Route::post('/import', [CustomerController::class, 'import'])->name('CustomerController.import');






// 
	// Route::get('customer',[CustomerController::class,'index']);


	
	
});

// Route::group(['middleware'=>['auth','Isstaff']],function()
Route::group(['prefix'=>'staff', 'middleware'=>['Isstaff','auth']], function()

{
// Route::get('/dashboard', [HomeController::class, 'staff'])->name('home');

	
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

	
	// Route::resource('customer',CustomerController::class,);
	// Route::get('customer',[CustomerController::class,'index'])->name('customer');

	Route::resource('staffcustomer',StaffController::class);



});
	
	
// });

// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){
//     Route::get('/staffindex', [App\Http\Controllers\StaffController::class, 'Isadmin'])->name('staff.index'); 
//  Route::get('/emphome', [App\Http\Controllers\HomeController::class, 'emp'])->name('emp.home'); // Employee Home

//     Route::resource('empproduct',EmpProductController::class); //Produ

// 	// Route::resource('staff',StaffController::class);

//     //
// });
// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){

//     Route::get('/staffrindex', [App\Http\Controllers\StaffController::class, 'staff'])->name('staff.index'); // Admin Home

//     Route::resource('staff',StaffController::class); 

// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>


<head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<style type="text/css">
  .row
  {
    color: blue;
    font-size: 20px;
  }
 
</style>
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
         
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-chat/ava3.png" alt="avatar" class="rounded-circle img-fluid" style="width: 150px; justify-content: center;">
           
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
                        </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Role</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{auth()->user()->role }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{auth()->user()->email }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{auth()->user()->name}} </p>
              </div>
            </div>
            <hr>
           
         </div>
       </div>
     </div>
   </div>
 </section>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>