routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\Staff1Controller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerExportController;
use App\Http\Controllers\CustomerImportController;

use App\Mail\WelcomeMail;


use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;


// use App\Http\Controllers\RoleController;
// use App\Http\Controllers\UserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/emails',function()
{
	Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail());
	return new WelcomeMail();
});

// Route::get('/emails', function () {
   
//     $customer = [
//         'name' => 'Mail from ItSolutionStuff.com',
//         'info' => 'This is for testing email using smtp'
//     ];
   
//     \Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail($customer));
   
// });

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
// Route::resource('admin/customer', CustomerController::class);


// Route::middleware(['auth:sanctum', 'verified'])->get('/customer.index', function () {
//     return view('customer');
// })->name('customer');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function()

{
Route::get('/dashboard', [HomeController::class, 'index'])->name('home');


	Route::get('staff',[Staff1Controller::class,'index'])->name('staff');

	Route::resource('customer',CustomerController::class);

	
	Route::resource('categorys',CategoryController::class);
	Route::resource('products',ProductController::class);



  Route::get('/export', [CustomerController::class, 'export'])->name('CustomerController.export');
    Route::get('/import-form', [CustomerController::class, 'importform'])->name('CustomerController.import-form');
    Route::post('/import', [CustomerController::class, 'import'])->name('CustomerController.import');






// 
	// Route::get('customer',[CustomerController::class,'index']);


	
	
});

// Route::group(['middleware'=>['auth','Isstaff']],function()
Route::group(['prefix'=>'staff', 'middleware'=>['Isstaff','auth']], function()

{
// Route::get('/dashboard', [HomeController::class, 'staff'])->name('home');

	
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

	
	// Route::resource('customer',CustomerController::class,);
	// Route::get('customer',[CustomerController::class,'index'])->name('customer');

	Route::resource('staffcustomer',StaffController::class);



});
	
	
// });

// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){
//     Route::get('/staffindex', [App\Http\Controllers\StaffController::class, 'Isadmin'])->name('staff.index'); 
//  Route::get('/emphome', [App\Http\Controllers\HomeController::class, 'emp'])->name('emp.home'); // Employee Home

//     Route::resource('empproduct',EmpProductController::class); //Produ

// 	// Route::resource('staff',StaffController::class);

//     //
// });
// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){

//     Route::get('/staffrindex', [App\Http\Controllers\StaffController::class, 'staff'])->name('staff.index'); // Admin Home

//     Route::resource('staff',StaffController::class); 

// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;



use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Haruncpi\LaravelUserActivity\Traits\Loggable;


class Category extends Model
{

    
    use HasFactory;
    use Loggable;
    
     protected $table = 'categories';

	    public $timestamps = true;

     protected $fillable = [
        'name','description',

    ];
      public function Product()
    {
        return $this->belongsToMany(Product::class,'productcategory');

    }
    
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Yajra\DataTables\DataTables;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    //     public function product()
    // {
    //     return $this->hasOne(Product::class);
    //     // note: we can also inlcude Mobile model like: 'App\Mobile'
    // }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

          if ($request->ajax()) {
            $data = Category::all();
           
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                       
   
                           $btn = '<a href="'.route('categorys.show', ['category'=>$row->id]).'" class="edit btn btn-info btn-sm">View</a>';
                           $btn = $btn.'&nbsp;&nbsp;<a href="'.route('categorys.edit', ['category' => $row->id]).'" class="edit btn btn-primary btn-sm">Edit</a>';

                           $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteProduct">Delete</a>';

    
                           return $btn;

                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('admin.categorys.indexcus');

        //  $categorys = Category::latest()->paginate(5);
    
        // return view('admin.categorys.index',compact('categorys'))
        //     ->with('i', (request()->input('page', 1) - 1) * 5);
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categorys.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([
            'name' => 'required',
            'description' => 'required',

        ]);
    
    
        Category::create($request->all());
     
        return redirect()->route('categorys.index')
                        ->with('success','created successfully.');
    }
    

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categorys.show',compact('category'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categorys.edit',compact('category'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)

    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',

        ]);
    
        $category->update($request->all());
    
        return redirect()->route('categorys.index')
                        ->with('success','updated successfully');
    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    // public function destroy(Category $category)
    public function destroy($id)

    {
         Category::find($id)->delete();
     
        return response()->json(['success'=>' deleted successfully.']);

         // $category->delete();

    
        return redirect()->route('categorys.index')
                        ->with('success','deleted successfully');
    
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/categorys/cre.blade.php
<form method="post">
    <input id="user1" value="user1"  name="invite[]" type="checkbox">
    <input id="user2" value="user2"  name="invite[]" type="checkbox">
    <input type="submit">
</form>
<?php
    if(isset($_POST['invite'])){
        $invite = $_POST['invite'];
        print_r($invite);
    }
?>

resources/views/admin/categorys/create.blade.php
@extends('admin.categorys.layout')
  
@section('content')
<head>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
   
  
  


    
    
 

<script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
    
</head>
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('categorys.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('categorys.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>  
       
              
       
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <input type="text" class="form-control"  name="description" placeholder="Description">
            </div>
        </div>

       
  <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit"  class="btn btn-primary">Submit</button>
        </div>
    </div>
</div>
</div>









<!-- <script > 
    var cricket = $('#cricket').val();
console.log(cricket);

 var chess = $('#chess').val();
console.log(chess);
 var baseball = $('#baseball').val();
console.log(baseball);</script>
    -->  
      

   
</form>
@endsection

resources/views/admin/categorys/edit.blade.php
@extends('admin.categorys.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('categorys.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('categorys.update',$category->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $category->name }}" class="form-control" placeholder="Name">
                </div>
            
             <div class="row">
            
        
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <input type="text" name="description" class="form-control" value="{{ $category->description }}">
                        
                </div>

            
            
        </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>

        
    
   
    </form>
@endsection

resources/views/admin/categorys/index.blade.php
@extends('admin.categorys.layout')

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <style type="text/css">
    .container
    {
        margin: 50px;
        padding: 0px
    }
</style>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>welcome</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('categorys.create') }}">Add</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Description</th>

            <th width="280px">Action</th>
        </tr>
        @foreach ($categorys as $product)
        <tr>

            <td>{{ ++$i }}</td>
            <td>{{ $product->name }}</td>
            
            <td>{{ $product->description }}</td>

            <td>
                <form action="{{ route('categorys.destroy',$product->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('categorys.show',$product->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('categorys.edit',$product->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
      

</x-app-layout>

resources/views/admin/categorys/indexcus.blade.php
  <x-app-layout>

<!DOCTYPE html>
<html>
<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>
    
<div class="container">
    <h1>Category page</h1>
    
    <div class="pull-right mb-2">
<a class="btn btn-success" onClick="add()"  href="{{ route('categorys.create') }}">Add Category</a>
</div>
                  
    <table class="table table-bordered data-table">
        <thead>
            <tr>
                     <th>No</th>
                     <th>Name</th>
                     <th>Description</th>
            <th width="280px">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
   
<div class="modal fade" id="ajaxModel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="productForm" name="productForm" class="form-horizontal">
                   <input type="hidden" name="product_id" id="product_id">
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">FirstName</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="FirstName" name="FirstName" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">LastName</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="LastName" name="LastName" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Address</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="Address" name="Address" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Phone</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="Phone" name="Phone" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Adharcard</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="Adharcard" name="Adharcard" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Pancard</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="Pancard" name="Pancard" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
     <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Referenes</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="Referenes" name="Referenes" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>
     
                  
      
                    <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                     </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    
</body>
    
<script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
     var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('categorys.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'name', name: 'name'},
            {data: 'description', name: 'description'},
          

            {data: 'action', name: 'action', orderable: false, searchable: false},

        ]
    });
     
    $('#createNewProduct').click(function () {
        $('#saveBtn').val("create-product");
        $('#product_id').val('');
        $('#productForm').trigger("reset");
        $('#modelHeading').html("Create New Product");
        $('#ajaxModel').modal('show');
    });
    
    $('body').on('click', '.editProduct', function () {
      var product_id = $(this).data('id');
      $.get("{{ route('categorys.index') }}" +'/' + product_id +'/edit', function (data) {
          $('#modelHeading').html("Edit Product");
          $('#saveBtn').val("edit-user");
          $('#ajaxModel').modal('show');
          $('#product_id').val(data.id);
          $('#name').val(data.name);
          $('#detail').val(data.detail);
      })
   });
    
    $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
    
        $.ajax({
          data: $('#productForm').serialize(),
          url: "{{ route('categorys.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
     
              $('#productForm').trigger("reset");
              $('#ajaxModel').modal('hide');
              table.draw();
         
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    });
    
    $('body').on('click', '.deleteProduct', function () {
     
        var product_id = $(this).data("id");
        confirm("Are You sure want to delete !");
      
        $.ajax({
            type: "DELETE",
            url: "{{ route('categorys.store') }}"+'/'+product_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
     
  });
</script>
</html>
</x-app-layout>

resources/views/admin/categorys/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Category list</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

resources/views/admin/categorys/show.blade.php
@extends('admin.categorys.layout')
  
@section('content')
    <style type="text/css">
    .container
    {
        margin-left: 60px;
        text-align: center;
        justify-content: center;
        padding: 50px 20px 30px 50px;
        margin: 25px;
        display: flex;
    }
</style>
<div class="container">
    <table class="table table-bordered">
     <thead>
        <tr>
            <td><strong>List of Categorys</td></strong>
        </tr>
    </thead>
    <tbody>
        <tr>
  
  <td>Name : {{ $category->name }} </td>
        </tr>
        <tr>
            <td>Description :  {{ $category->description }}</td>
        </tr>
       
            
            <td><a class="btn btn-primary" href="{{ route('categorys.index') }}"> Back</a></td>
        </tbody>
    </table>
</div>
</div>

@endsection