routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\Staff1Controller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerExportController;
use App\Http\Controllers\CustomerImportController;

use App\Mail\WelcomeMail;


use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;


// use App\Http\Controllers\RoleController;
// use App\Http\Controllers\UserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/emails',function()
{
	Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail());
	return new WelcomeMail();
});

// Route::get('/emails', function () {
   
//     $customer = [
//         'name' => 'Mail from ItSolutionStuff.com',
//         'info' => 'This is for testing email using smtp'
//     ];
   
//     \Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail($customer));
   
// });

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
// Route::resource('admin/customer', CustomerController::class);


// Route::middleware(['auth:sanctum', 'verified'])->get('/customer.index', function () {
//     return view('customer');
// })->name('customer');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function()

{
Route::get('/dashboard', [HomeController::class, 'index'])->name('home');


	Route::get('staff',[Staff1Controller::class,'index'])->name('staff');

	Route::resource('customer',CustomerController::class);

	
	Route::resource('categorys',CategoryController::class);
	Route::resource('products',ProductController::class);



  Route::get('/export', [CustomerController::class, 'export'])->name('CustomerController.export');
    Route::get('/import-form', [CustomerController::class, 'importform'])->name('CustomerController.import-form');
    Route::post('/import', [CustomerController::class, 'import'])->name('CustomerController.import');






// 
	// Route::get('customer',[CustomerController::class,'index']);


	
	
});

// Route::group(['middleware'=>['auth','Isstaff']],function()
Route::group(['prefix'=>'staff', 'middleware'=>['Isstaff','auth']], function()

{
// Route::get('/dashboard', [HomeController::class, 'staff'])->name('home');

	
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

	
	// Route::resource('customer',CustomerController::class,);
	// Route::get('customer',[CustomerController::class,'index'])->name('customer');

	Route::resource('staffcustomer',StaffController::class);



});
	
	
// });

// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){
//     Route::get('/staffindex', [App\Http\Controllers\StaffController::class, 'Isadmin'])->name('staff.index'); 
//  Route::get('/emphome', [App\Http\Controllers\HomeController::class, 'emp'])->name('emp.home'); // Employee Home

//     Route::resource('empproduct',EmpProductController::class); //Produ

// 	// Route::resource('staff',StaffController::class);

//     //
// });
// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){

//     Route::get('/staffrindex', [App\Http\Controllers\StaffController::class, 'staff'])->name('staff.index'); // Admin Home

//     Route::resource('staff',StaffController::class); 

// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;
use Haruncpi\LaravelUserActivity\Traits\Loggable;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;


class Product extends Model
{
    use HasFactory;
    use Loggable;
    
         protected $table = 'products';

      protected $fillable = [
        'name', 'price','description',
            ];
             public function Category()
    {
         return $this->belongsToMany(Category::class,'productcategory');

    }

}

app/Http/Controllers/ProductController.php
<?php
  
namespace App\Http\Controllers;
  
use App\Models\Product;
use App\Models\Category;
use App\Models\ProductCategory;
use Illuminate\Http\Request; 
use Illuminate\Support\Facades\DB;


class ProductController extends Controller
{
       

   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()

    {

        
       


        
   $product = DB::table('productcategory')
            ->join('products', 'products.id', '=', 'productcategory.product_id')
            ->join('categories', 'categories.id', '=', 'productcategory.category_id')
            ->select('products.*', 'categories.name as category_name')
            ->get();
           
        return view('admin.products.index',compact('product'));

        // $products = Product::latest()->paginate(5);
                // $products = Product::all(["id","name"]);

        // return view('admin.products.index',compact('products','category'));
       // return view('admin.products.index',compact('products'));

    
        // return view('products.index',compact('products'))
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // return view('products.create');
        // $category = DB::table('categories')->pluck("name","id");
        $category=Category::all(["id","name"]);

        // return view('admin.products.create');
return view('admin.products.create',['category'=>$category]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      //   $request->validate([
      //       'name' => 'required',
      //       'description' => 'required',
      //   ]);
  
      //   $input = $request->all();
      // Product::create($input);
         $product = new Product;
        $product->name   = $request['name'];
        $product->price   = $request['price'];
        $product->description   = $request['description'];
        $product->save();
        $product->Category()->attach($request->category_id);
     
        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }
     
    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    // public function show(Product $product)
    public function show($id)

    {
  $product = DB::table('productcategory')
            ->join('products', 'products.id', '=', 'productcategory.product_id')
            ->join('categories', 'categories.id', '=', 'productcategory.category_id')
            ->where('products.id',$id)
            ->select('products.*', 'categories.name as category_name')
            ->first();
            //print_r($product);
            //exit();
        return view('admin.products.show',compact('product'));
    }
     
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
     // public function edit(Product $product)
     // {()

        // $category=Category::all(["id","name"]);
public function edit($id)
{
    $product = Product::where('id',$id)->select('*')->first();
    $product1 = DB::table('categories')->join('productcategory','categories.id','=','productcategory.category_id')->where('productcategory.product_id',$id)->pluck('categories.id')->toArray();
            $category = Category::all(["id","name"]);
              // print_r($category);
              // exit();  
     
       return view('admin.products.edit',compact('product','category','product1'));
}    
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    // public function update(Request $request, Product $product)
    public function update(Request $request, $id)

    {
        $product = Product::find($id);
        $product->name   = $request['name'];
        $product->price   = $request['price'];
        $product->description   = $request['description'];
       $product->update();
        // Sync method
        $product->Category()->sync($request->category_id);
        
        // $product=Product::find($id);
        //             $category = Category::all(["id","name"]);

        // $input = $request->all();


        // $product->update($input);

        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // public function destroy(Product $product)
    public function destroy($id)


    {
       $product=Product::find($id);
         // $product->active_status="0";
         // $product->delete_status="1";
        // $product->delete();
     
        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/products/create.blade.php
@extends('admin.products.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
        </div>
    </div>
</div>
     
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
     
<form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">View customer Details</div>
            <div class="card-body">

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        



            <div class="form-group">
                <label for="category">Select Category:</label>
                <select name="category_id" id="category" class="form-control" style="width:250px">
                   <!--  <option value="">--- Select Category ---</option>
                    @foreach ($category as $key => $value)
                    <option value="{{ $key }}">{{ $value }}</option>
                    @endforeach
                </select>
            </div> -->

                    <option value="">--- Select Category ---</option>
                    @foreach ($category as $category)
                    <option value="{{$category->id }}">{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
       
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description"></textarea>
            </div>
        </div>
        
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                <input type="number" name="price" class="form-control" placeholder="price">
            </div>
        </div>

       
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
</form>
@endsection

resources/views/admin/products/edit.blade.php
@extends('admin.products.layout')
   
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
   
   <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Edit Product Details</div>
            <div class="card-body">
                

              
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $product->name }}" class="form-control">
                </div>
            </div>
              <div class="form-group">
                        <label>Category</label><span class="text-danger">*</span>
                        <select class="form-control"  id="cat" name="category_id">
                            <option value="">select</option>
                            @foreach ($category as $category)
                                <option value="{{ $category->id }}" {{$product1==$category->id ? "selected" : ""}}


 
                                    selected>{{ $category->name}}</option>
                            @endforeach
                        </select>

 

 
</div>

                
            
            
           
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{ $product->description }}</textarea>
                </div>
            </div>
             <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price:</strong>
                    <input type="number" name="price" value="{{ $product->price }}" class="form-control" placeholder="Price">
                </div>
            </div>

           
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>

resources/views/admin/products/index.blade.php
@extends('admin.products.layout')

     
<x-app-layout>
    
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Products</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
            </div>
        </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
     
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Category_name</th>

            <th>Description</th>
            <th>Price</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($product as $product)
        <tr>


            <td>{{ $product->id }}</td>

            <td>{{ $product->name }}</td>
            <td>{{ $product->category_name }}</td>



            <td>{{ $product->description }}</td>
            <td>{{$product->price}}</td>


            <td>
                <form action="{{ route('products.destroy',$product->id) }}" method="POST">
     
                    <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>
      
                    <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>
     
                    @csrf
                    @method('DELETE')
        
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
</x-app-layout>

resources/views/admin/products/indexcus.blade.php
  <x-app-layout>

<!DOCTYPE html>
<html>
<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>
    
<div class="container">
    <h1>products page</h1>
    
    <div class="pull-right mb-2">
<a class="btn btn-success" onClick="add()"  href="{{ route('products.create') }}">Add </a>
</div>
                  
    <table class="table table-bordered data-table">
        <thead>
            <tr>
                     <th>No</th>
                     <th>Name</th>
                     <th>Category_name</th>
                     <th>Description</th>
                     <th>Price</th>
            <th width="280px">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
   

    
    
<script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
     var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('products.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'name', name: 'name'},
            {data: 'description', name: 'description'},
            {data: 'price', name: 'price'},

          

            {data: 'action', name: 'action', orderable: false, searchable: false},

        ]
    });
     
    $('#createNewProduct').click(function () {
        $('#saveBtn').val("create-product");
        $('#product_id').val('');
        $('#productForm').trigger("reset");
        $('#modelHeading').html("Create New Product");
        $('#ajaxModel').modal('show');
    });
    
    $('body').on('click', '.editProduct', function () {
      var product_id = $(this).data('id');
      $.get("{{ route('products.index') }}" +'/' + product_id +'/edit', function (data) {
          $('#modelHeading').html("Edit Product");
          $('#saveBtn').val("edit-user");
          $('#ajaxModel').modal('show');
          $('#product_id').val(data.id);
          $('#name').val(data.name);
          $('#detail').val(data.detail);
      })
   });
    
    $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
    
        $.ajax({
          data: $('#productForm').serialize(),
          url: "{{ route('products.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
     
              $('#productForm').trigger("reset");
              $('#ajaxModel').modal('hide');
              table.draw();
         
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    });
    
    $('body').on('click', '.deleteProduct', function () {
     
        var product_id = $(this).data("id");
        confirm("Are You sure want to delete !");
      
        $.ajax({
            type: "DELETE",
            url: "{{ route('products.store') }}"+'/'+product_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
     
  });
</script>
</html>
</x-app-layout>

resources/views/admin/products/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>product page</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    
   

    
</head>
<body>
<div class="container">
    @yield('content')
</div>


</body>
</html>
  

resources/views/admin/products/show.blade.php
@extends('admin.products.layout')
@section('content')
  <x-app-layout>
<style type="text/css">
    .col-md-6
    {
        color: blue;

    }
    .card
    {
        justify-content: center;
        text-align: center;
    }
    
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">View customer Details</div>
            <div class="card-body">

                <div class="row md-12">
                    <div class="col-md-3">
                        <label class="my-3"><b>Name</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $product->name }}</label>
                    </div>
                </div>

                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Description</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $product->description }}</label>
                    </div>
                </div>

<div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Category_name</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{$product->category_name }}</label>
                    </div>
                
                </div>

        
        

                <div class="row md-3">
                    <div class="col-md-3">
                        <label class="my-3"><b>Price</b></label>
                    </div>
                    <div class="col-md-8">
                    <label class="my-3">{{ $product->price }}</label>
                    </div>
                </div>

                <a href="{{ route('products.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
</div>
</div>
</x-app-layout>
@endsection