routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\Staff1Controller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerExportController;
use App\Http\Controllers\CustomerImportController;

use App\Mail\WelcomeMail;


use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;


// use App\Http\Controllers\RoleController;
// use App\Http\Controllers\UserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/emails',function()
{
	Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail());
	return new WelcomeMail();
});

// Route::get('/emails', function () {
   
//     $customer = [
//         'name' => 'Mail from ItSolutionStuff.com',
//         'info' => 'This is for testing email using smtp'
//     ];
   
//     \Mail::to('sandysandyrg123@gmail.com')->send(new WelcomeMail($customer));
   
// });

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
// Route::resource('admin/customer', CustomerController::class);


// Route::middleware(['auth:sanctum', 'verified'])->get('/customer.index', function () {
//     return view('customer');
// })->name('customer');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function()

{
Route::get('/dashboard', [HomeController::class, 'index'])->name('home');


	Route::get('staff',[Staff1Controller::class,'index'])->name('staff');

	Route::resource('customer',CustomerController::class);

	
	Route::resource('categorys',CategoryController::class);
	Route::resource('products',ProductController::class);



  Route::get('/export', [CustomerController::class, 'export'])->name('CustomerController.export');
    Route::get('/import-form', [CustomerController::class, 'importform'])->name('CustomerController.import-form');
    Route::post('/import', [CustomerController::class, 'import'])->name('CustomerController.import');






// 
	// Route::get('customer',[CustomerController::class,'index']);


	
	
});

// Route::group(['middleware'=>['auth','Isstaff']],function()
Route::group(['prefix'=>'staff', 'middleware'=>['Isstaff','auth']], function()

{
// Route::get('/dashboard', [HomeController::class, 'staff'])->name('home');

	
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

	
	// Route::resource('customer',CustomerController::class,);
	// Route::get('customer',[CustomerController::class,'index'])->name('customer');

	Route::resource('staffcustomer',StaffController::class);



});
	
	
// });

// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){
//     Route::get('/staffindex', [App\Http\Controllers\StaffController::class, 'Isadmin'])->name('staff.index'); 
//  Route::get('/emphome', [App\Http\Controllers\HomeController::class, 'emp'])->name('emp.home'); // Employee Home

//     Route::resource('empproduct',EmpProductController::class); //Produ

// 	// Route::resource('staff',StaffController::class);

//     //
// });
// Route::group(['prefix'=>'admin', 'middleware'=>['Isadmin','auth']], function(){

//     Route::get('/staffrindex', [App\Http\Controllers\StaffController::class, 'staff'])->name('staff.index'); // Admin Home

//     Route::resource('staff',StaffController::class); 

// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/staffcustomer/edit.blade.php
@extends('admin.staffcustomer.layout')
   
@section('content')

    <x-app-layout>

    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Edit customer</h2>

           <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('staffcustomer.index') }}"> Back</a>
            </div>
        </div>
    </div>
 
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('staffcustomer.update',$customer->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>FirstName:</strong>
                    <input type="text" name="FirstName" value="{{ $customer->FirstName }}" class="form-control" >
                </div>
            </div>
        </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">
                    <strong>LastName:</strong>
                    <input type="text" name="LastName" value="{{ $customer->LastName }}" class="form-control" >
                </div>
            </div>
        </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">

            
                <div class="form-group">
                    <strong>Address:</strong>
                    <input type="text" name="Address" value="{{ $customer->Address }}" class="form-control" >
                </div>
            </div>
        </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
            
                <div class="form-group">
                    <strong>Phone:</strong>
                    <input type="number" name="Phone" value="{{ $customer->Phone }}" class="form-control" >
                </div>
            </div>
        </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
        
                <div class="form-group">
                    <strong>PanCard:</strong>
                    <input type="number" name="PanCard" value="{{ $customer->PanCard }}" class="form-control" >
                </div>
            </div>
        </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
            
                <div class="form-group">
                    <strong>AdharCard:</strong>
                    <input type="number" name="AdharCard" value="{{ $customer->AdharCard }}" class="form-control" >
                </div>
            </div>
        </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
        
                <div class="form-group">
                    <strong>Reference:</strong>
                    <input type="text" name="Referenes" value="{{ $customer->Referenes }}" class="form-control" >
                </div>
            </div>
            </div>
           
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>

        </div>
    
    
        
    </form>
</div>
</x-app-layout>
   

@endsection

resources/views/admin/staffcustomer/index.blade.php
@extends('admin.staffcustomer.layout')
     

    <x-app-layout>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>customer</h2>
            </div>
           
        </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
     
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Phone</th>
            <th>Address</th>
            <th>PanCard</th>
            <th>AdharCard</th>

            <th>Referenes</th>
            <th width="280px">Action</th>
        </tr>
        

        @foreach ($customer as $customer)
        <tr>


            <td>{{ $customer->id }}</td>

            <td>{{$customer->FirstName}}</td>
            <td>{{$customer->LastName}}</td>
            <td>{{$customer->Phone}}</td>

            <td>{{$customer->Address}}</td>
            <td>{{$customer->AdharCard}}</td>
            <td>{{$customer->PanCard}}</td>
            <td>{{$customer->Referenes}}</td>

            <td>
     
                   
      
                    <a class="btn btn-primary" href="{{ route('staffcustomer.edit',$customer->id) }}">Edit</a>
     
        
                </form>
            </td>
        </tr>
        @endforeach
    
    </table>
</x-app-layout>

    
        

resources/views/admin/staffcustomer/indexstaff.blade.php
@extends('admin.customer.layout')
     
@section('content')

  <x-app-layout>
    
<!DOCTYPE html>
<html>
<head>
   <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
   
   
</head>
<body>
   <div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left">
<h2>CUSTOMER PAGE</h2>
</div>
<div class="pull-right mb-2">
<a class="btn btn-success" onClick="add()"  href="{{ route('customer.create') }}">Add customer</a>


                    
                </div>
                </div>
                 <div class="float-left">
                    <a href="{{ route('admin.customer.export') }}" class="btn btn-success mr-3">Export</a>
                </div>
               

</div>

  <div class="container">
    <table class="table table-bordered data-table" >
        <thead>
            <tr>
               <th>No</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Phone</th>
            <th>Address</th>
            <th>PanCard</th>
            <th>AdharCard</th>

            <th>Referenes</th>
                <th width="100px">Action</th>
            </tr>

</thead>
        <tbody>
        </tbody>
    </table>
</div>

   
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
 <script type="text/javascript">

  $(function () {
     $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('customer.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'FirstName', name: 'FirstName'},
            {data: 'LastName', name: 'LastName'},
            {data: 'Address', name: 'Address'},
            {data: 'Phone', name: 'Phone'},
            {data: 'AdharCard', name: 'AdharCard'},
            {data: 'PanCard', name: 'PanCard'},
            {data: 'Referenes', name: 'Referenes'},


            {data: 'action', name: 'action', orderable: false, searchable: false},

        ]
    });
   
   $('body').on('click', '.categorys', function () {
     
        var product_id = $(this).data("id");
        confirm("Are You sure want to delete !");
      
        $.ajax({
            type: "DELETE",
            url: "{{ route('customer.store') }}"+'/'+product_id,
            success: function (data) {
                table.draw();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });
  });
</script>
</html>
</x-app-layout>

@endsetion

resources/views/admin/staffcustomer/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Customer page</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
   
    

    
</head>
<body>



</body>
</html>
  
<!-- <div class="container">
    @yield('content')
</div>
   
</body>
</html>
 -->